// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// utl_cpp_ser
Rcpp::List utl_cpp_ser(const Rcpp::NumericMatrix& score, const Rcpp::List& Pj, const Rcpp::List& Flist, const Rcpp::NumericVector& V, const Rcpp::NumericVector& weights, bool moments, int topcount);
RcppExport SEXP _SuSiEUTL_utl_cpp_ser(SEXP scoreSEXP, SEXP PjSEXP, SEXP FlistSEXP, SEXP VSEXP, SEXP weightsSEXP, SEXP momentsSEXP, SEXP topcountSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Pj(PjSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Flist(FlistSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type moments(momentsSEXP);
    Rcpp::traits::input_parameter< int >::type topcount(topcountSEXP);
    rcpp_result_gen = Rcpp::wrap(utl_cpp_ser(score, Pj, Flist, V, weights, moments, topcount));
    return rcpp_result_gen;
END_RCPP
}
// utl_cpp_component_moments
Rcpp::List utl_cpp_component_moments(const Rcpp::NumericMatrix& score, const Rcpp::List& Pj, const Rcpp::List& Flist, const Rcpp::NumericVector& V);
RcppExport SEXP _SuSiEUTL_utl_cpp_component_moments(SEXP scoreSEXP, SEXP PjSEXP, SEXP FlistSEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Pj(PjSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Flist(FlistSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(utl_cpp_component_moments(score, Pj, Flist, V));
    return rcpp_result_gen;
END_RCPP
}
// utl_cpp_ser_reduce
Rcpp::List utl_cpp_ser_reduce(const Rcpp::NumericMatrix& score, const Rcpp::List& Pj, const Rcpp::NumericMatrix& lbf, const Rcpp::NumericVector& component_mean, const Rcpp::NumericVector& component_covariance, const Rcpp::NumericVector& weights, bool moments, int topcount);
RcppExport SEXP _SuSiEUTL_utl_cpp_ser_reduce(SEXP scoreSEXP, SEXP PjSEXP, SEXP lbfSEXP, SEXP component_meanSEXP, SEXP component_covarianceSEXP, SEXP weightsSEXP, SEXP momentsSEXP, SEXP topcountSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Pj(PjSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type lbf(lbfSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type component_mean(component_meanSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type component_covariance(component_covarianceSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type moments(momentsSEXP);
    Rcpp::traits::input_parameter< int >::type topcount(topcountSEXP);
    rcpp_result_gen = Rcpp::wrap(utl_cpp_ser_reduce(score, Pj, lbf, component_mean, component_covariance, weights, moments, topcount));
    return rcpp_result_gen;
END_RCPP
}
// utl_cpp_common_ser_context
Rcpp::List utl_cpp_common_ser_context(const Rcpp::NumericMatrix& P0, const Rcpp::List& Flist, const Rcpp::NumericVector& V, bool moments);
RcppExport SEXP _SuSiEUTL_utl_cpp_common_ser_context(SEXP P0SEXP, SEXP FlistSEXP, SEXP VSEXP, SEXP momentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Flist(FlistSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type V(VSEXP);
    Rcpp::traits::input_parameter< bool >::type moments(momentsSEXP);
    rcpp_result_gen = Rcpp::wrap(utl_cpp_common_ser_context(P0, Flist, V, moments));
    return rcpp_result_gen;
END_RCPP
}
// utl_cpp_common_ser_lbf
Rcpp::List utl_cpp_common_ser_lbf(const Rcpp::NumericMatrix& score, const Rcpp::List& context);
RcppExport SEXP _SuSiEUTL_utl_cpp_common_ser_lbf(SEXP scoreSEXP, SEXP contextSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type context(contextSEXP);
    rcpp_result_gen = Rcpp::wrap(utl_cpp_common_ser_lbf(score, context));
    return rcpp_result_gen;
END_RCPP
}
// utl_cpp_common_component_moments
Rcpp::List utl_cpp_common_component_moments(const Rcpp::NumericMatrix& score, const Rcpp::List& context);
RcppExport SEXP _SuSiEUTL_utl_cpp_common_component_moments(SEXP scoreSEXP, SEXP contextSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type context(contextSEXP);
    rcpp_result_gen = Rcpp::wrap(utl_cpp_common_component_moments(score, context));
    return rcpp_result_gen;
END_RCPP
}
// utl_cpp_common_ser_lbf_moments
Rcpp::List utl_cpp_common_ser_lbf_moments(const Rcpp::NumericMatrix& score, const Rcpp::List& context);
RcppExport SEXP _SuSiEUTL_utl_cpp_common_ser_lbf_moments(SEXP scoreSEXP, SEXP contextSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type context(contextSEXP);
    rcpp_result_gen = Rcpp::wrap(utl_cpp_common_ser_lbf_moments(score, context));
    return rcpp_result_gen;
END_RCPP
}
// utl_cpp_v_cache
Rcpp::List utl_cpp_v_cache(const Rcpp::NumericMatrix& M, const Rcpp::NumericMatrix& Bk, const Rcpp::NumericMatrix& bhat, const Rcpp::NumericMatrix& N);
RcppExport SEXP _SuSiEUTL_utl_cpp_v_cache(SEXP MSEXP, SEXP BkSEXP, SEXP bhatSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Bk(BkSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type bhat(bhatSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(utl_cpp_v_cache(M, Bk, bhat, N));
    return rcpp_result_gen;
END_RCPP
}
// utl_cpp_v_loglik
Rcpp::NumericVector utl_cpp_v_loglik(const Rcpp::NumericMatrix& s, const Rcpp::NumericMatrix& u, double V);
RcppExport SEXP _SuSiEUTL_utl_cpp_v_loglik(SEXP sSEXP, SEXP uSEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(utl_cpp_v_loglik(s, u, V));
    return rcpp_result_gen;
END_RCPP
}
// utl_cpp_vraw
Rcpp::NumericVector utl_cpp_vraw(const Rcpp::NumericMatrix& bhat, const Rcpp::NumericMatrix& N);
RcppExport SEXP _SuSiEUTL_utl_cpp_vraw(SEXP bhatSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type bhat(bhatSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(utl_cpp_vraw(bhat, N));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SuSiEUTL_utl_cpp_ser", (DL_FUNC) &_SuSiEUTL_utl_cpp_ser, 7},
    {"_SuSiEUTL_utl_cpp_component_moments", (DL_FUNC) &_SuSiEUTL_utl_cpp_component_moments, 4},
    {"_SuSiEUTL_utl_cpp_ser_reduce", (DL_FUNC) &_SuSiEUTL_utl_cpp_ser_reduce, 8},
    {"_SuSiEUTL_utl_cpp_common_ser_context", (DL_FUNC) &_SuSiEUTL_utl_cpp_common_ser_context, 4},
    {"_SuSiEUTL_utl_cpp_common_ser_lbf", (DL_FUNC) &_SuSiEUTL_utl_cpp_common_ser_lbf, 2},
    {"_SuSiEUTL_utl_cpp_common_component_moments", (DL_FUNC) &_SuSiEUTL_utl_cpp_common_component_moments, 2},
    {"_SuSiEUTL_utl_cpp_common_ser_lbf_moments", (DL_FUNC) &_SuSiEUTL_utl_cpp_common_ser_lbf_moments, 2},
    {"_SuSiEUTL_utl_cpp_v_cache", (DL_FUNC) &_SuSiEUTL_utl_cpp_v_cache, 4},
    {"_SuSiEUTL_utl_cpp_v_loglik", (DL_FUNC) &_SuSiEUTL_utl_cpp_v_loglik, 3},
    {"_SuSiEUTL_utl_cpp_vraw", (DL_FUNC) &_SuSiEUTL_utl_cpp_vraw, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_SuSiEUTL(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
