# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

utl_cpp_ser <- function(score, Pj, Flist, V, weights, moments = TRUE, topcount = 0L) {
    .Call(`_SuSiEUTL_utl_cpp_ser`, score, Pj, Flist, V, weights, moments, topcount)
}

utl_cpp_component_moments <- function(score, Pj, Flist, V) {
    .Call(`_SuSiEUTL_utl_cpp_component_moments`, score, Pj, Flist, V)
}

utl_cpp_ser_reduce <- function(score, Pj, lbf, component_mean, component_covariance, weights, moments = TRUE, topcount = 0L) {
    .Call(`_SuSiEUTL_utl_cpp_ser_reduce`, score, Pj, lbf, component_mean, component_covariance, weights, moments, topcount)
}

utl_cpp_common_ser_context <- function(P0, Flist, V, moments = TRUE) {
    .Call(`_SuSiEUTL_utl_cpp_common_ser_context`, P0, Flist, V, moments)
}

utl_cpp_common_ser_lbf <- function(score, context) {
    .Call(`_SuSiEUTL_utl_cpp_common_ser_lbf`, score, context)
}

utl_cpp_common_component_moments <- function(score, context) {
    .Call(`_SuSiEUTL_utl_cpp_common_component_moments`, score, context)
}

utl_cpp_common_ser_lbf_moments <- function(score, context) {
    .Call(`_SuSiEUTL_utl_cpp_common_ser_lbf_moments`, score, context)
}

utl_cpp_v_cache <- function(M, Bk, bhat, N) {
    .Call(`_SuSiEUTL_utl_cpp_v_cache`, M, Bk, bhat, N)
}

utl_cpp_v_loglik <- function(s, u, V) {
    .Call(`_SuSiEUTL_utl_cpp_v_loglik`, s, u, V)
}

utl_cpp_vraw <- function(bhat, N) {
    .Call(`_SuSiEUTL_utl_cpp_vraw`, bhat, N)
}
